version: "3.9"
services:
  api:
    image: put.net/todo
    build:
      dockerfile: ../docker/Dockerfile
      context: ../src
    environment:
      ConnectionStrings__Default: Server=db;Database=todo;Uid=user;Pwd=password;
    ports:
      - "5274:8080"
    expose:
      - 5274
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "--silent"]
      timeout: 3s
      retries: 5
      start_period: 0s
      interval: 5s
    networks:
      - default
      
networks:
  default:
    driver: bridge